# Generated by Django 3.2 on 2022-09-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_header', models.CharField(default='Shop Online', max_length=20, null=True)),
                ('slider_info', models.TextField(max_length=120, null=True)),
            ],
        ),
    ]
